#define STRING              1
#define INTEGER             2
#define HEX                 3
#define FLOAT               4
#define WHITESPACE          5
#define BRACKETS            6
#define END_BRACKETS        7
#define MANUFACTURER        8 
#define DEVICE_TYPE         9
#define DEVICE_REVISION     10
#define DD_REVISION         11
#define VARIABLE            12
#define LABEL               13
#define HELP                14
#define CLASS               15
#define TYPE                16
#define HANDLING            17
#define DEFAULT_VALUE       18
#define OTHER               19
